services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - video_data:/app/assets/videos
      - thumbnail_data:/app/assets/thumbnails
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - video_data:/usr/share/nginx/html/videos:ro
      - thumbnail_data:/usr/share/nginx/html/thumbnails:ro

volumes:
  video_data:
  thumbnail_data:
